"use client";

import type { PlayerDetail, Sponsor, StaffUser } from "../shared/types";
import { useModalDismiss } from "../Modal/Modal.hooks";
import { usePlayerForm } from "./Players.hooks";

export function ManualPlayerModal({ user, sponsors, initialSponsorId = "", player, close, saved }: { user: StaffUser; sponsors: Sponsor[]; initialSponsorId?: string; player?: PlayerDetail; close: () => void; saved: () => Promise<void> }) {
  useModalDismiss(close);
  const { form, update, busy, error, complete, submit } = usePlayerForm({ user, sponsors, initialSponsorId, player, close, saved });
  return <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) close(); }}><form className="modal-card" role="dialog" aria-modal="true" aria-labelledby="manual-player-title" onSubmit={submit}><div className="modal-header"><div><p>{player ? "DEELNEMER BEHEREN" : "BETALING OVERSLAAN"}</p><h2 id="manual-player-title">{player ? "Deelnemer wijzigen" : "Deelnemer handmatig toevoegen"}</h2></div><button type="button" className="modal-close" onClick={close} aria-label="Sluiten">×</button></div><div className="modal-grid"><label>Naam<input autoFocus required value={form.name} onChange={event => update("name", event.target.value)} /></label><label>E-mailadres<input type="email" required value={form.email} onChange={event => update("email", event.target.value)} /></label><label>Telefoonnummer<input required value={form.phone} onChange={event => update("phone", event.target.value)} /></label><label>Geboortedatum<input type="date" required value={form.date_of_birth} onChange={event => update("date_of_birth", event.target.value)} /></label><label>KNLTB bondsnummer<input value={form.knltb_number} onChange={event => update("knltb_number", event.target.value)} /></label><div className="modal-ratings"><label>Enkel<input value={form.singles_rating} onChange={event => update("singles_rating", event.target.value)} /></label><label>Dubbel<input value={form.doubles_rating} onChange={event => update("doubles_rating", event.target.value)} /></label></div><label className="modal-wide">Opkomstnummer<input required value={form.entrance_song_query} onChange={event => update("entrance_song_query", event.target.value)} placeholder="Artiest – titel" /></label><label>Sponsor (optioneel)<select value={form.sponsor_id} onChange={event => update("sponsor_id", event.target.value)}><option value="">Geen sponsor</option>{sponsors.map(sponsor => <option key={sponsor.id} value={sponsor.id}>{sponsor.name} · {sponsor.tier_name}</option>)}</select></label>{player && <label>Deelnamestatus<select value={form.registration_status} onChange={event => update("registration_status", event.target.value)}><option value="confirmed">Betaald</option><option value="payment_pending">Betaling open</option><option value="cancelled">Geannuleerd</option><option value="refunded">Terugbetaald</option></select></label>}</div><p className="hint">KNLTB bondsnummer óf zowel enkel- als dubbelsterkte is verplicht.</p>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Annuleren</button><button className="primary" disabled={!complete || busy}>{busy ? "Opslaan…" : player ? "Wijzigingen opslaan" : "Direct als betaald toevoegen"}</button></div></form></div>;
}
