"use client";

import type { StaffUser } from "../shared/types";
import { CourtRow } from "./CourtRow";
import { useSettings } from "./Settings.hooks";

const numeric = (value: string) => Number.parseInt(value, 10) || 0;

export function Settings({ tournamentId, user, onTournamentSaved }: { tournamentId: number; user: StaffUser; onTournamentSaved: () => Promise<void> }) {
  const settings = useSettings({ tournamentId, user, onTournamentSaved });
  if (settings.loading) return <section className="panel full"><div className="empty-state">Instellingen laden…</div></section>;
  if (!settings.form) return <section className="panel full"><div className="empty-state"><strong>Instellingen niet beschikbaar</strong><span>{settings.error}</span></div></section>;
  const form = settings.form;

  return <div className="settings-page">
    <form onSubmit={settings.save}>
      <section className="panel settings-heading"><div><p>TOERNOOI CONFIGURATIE</p><h2>Matchpoint Tournament</h2><span>Wijzigingen gelden direct voor de inschrijving en vormen straks de basis voor de loting en planning.</span></div><button className="primary" disabled={settings.busy}>{settings.busy ? "Opslaan…" : "Wijzigingen opslaan"}</button></section>
      {settings.error && <p className="settings-message error">{settings.error}</p>}
      {settings.success && <p className="settings-message success">{settings.success}</p>}
      <div className="settings-grid">
        <section className="panel settings-section"><div className="settings-section-title"><span>01</span><div><h3>Algemeen</h3><p>Naam, status, datum en locatie.</p></div></div><div className="settings-fields"><label className="wide">Toernooinaam<input required value={form.name} onChange={event => settings.update("name", event.target.value)} /></label><label>Status<select value={form.status} onChange={event => settings.update("status", event.target.value as typeof form.status)}><option value="draft">Concept</option><option value="registration">Inschrijving open</option><option value="live">Toernooi live</option><option value="completed">Afgerond</option><option value="archived">Gearchiveerd</option></select></label><label>Start toernooi<input required type="datetime-local" value={form.starts_at} onChange={event => settings.update("starts_at", event.target.value)} /></label><label>Club / locatie<input required value={form.venue_name} onChange={event => settings.update("venue_name", event.target.value)} /></label><label className="wide">Adres<input required value={form.venue_address} onChange={event => settings.update("venue_address", event.target.value)} /></label></div></section>
        <section className="panel settings-section"><div className="settings-section-title"><span>02</span><div><h3>Inschrijving</h3><p>Beschikbaarheid, capaciteit en betaling.</p></div></div><div className="settings-fields"><label>Inschrijving sluit<input required type="datetime-local" value={form.registration_deadline_at} onChange={event => settings.update("registration_deadline_at", event.target.value)} /></label><label>Maximum deelnemers<select value={form.capacity} onChange={event => settings.update("capacity", numeric(event.target.value))}>{[32, 64, 128, 256].map(value => <option key={value} value={value}>{value} spelers</option>)}</select></label><label>Inschrijfbedrag (€)<input required type="number" min="0" max="1000" step="0.01" value={form.registration_price_cents / 100} onChange={event => settings.update("registration_price_cents", Math.round(Number(event.target.value) * 100))} /></label><label>E-mail dagrapportage<input type="email" value={form.daily_summary_email ?? ""} onChange={event => settings.update("daily_summary_email", event.target.value)} /></label><label>Tijd dagrapportage<input type="time" value={form.daily_summary_time} onChange={event => settings.update("daily_summary_time", event.target.value)} /></label></div></section>
        <section className="panel settings-section"><div className="settings-section-title"><span>03</span><div><h3>Wedstrijden en pauzes</h3><p>Standaardwaarden blijven per ronde overschrijfbaar.</p></div></div><div className="settings-fields compact"><label>Wedstrijdduur<input type="number" min="1" max="60" value={form.default_match_minutes} onChange={event => settings.update("default_match_minutes", numeric(event.target.value))} /><small>minuten</small></label><label>Kwartfinale en verder<input type="number" min="1" max="60" value={form.final_round_match_minutes} onChange={event => settings.update("final_round_match_minutes", numeric(event.target.value))} /><small>minuten</small></label><label>Pauze iedere<input type="number" min="5" max="240" value={form.break_every_minutes} onChange={event => settings.update("break_every_minutes", numeric(event.target.value))} /><small>minuten</small></label><label>Duur pauze<input type="number" min="1" max="60" value={form.break_duration_minutes} onChange={event => settings.update("break_duration_minutes", numeric(event.target.value))} /><small>minuten</small></label></div></section>
        <section className="panel settings-section"><div className="settings-section-title"><span>04</span><div><h3>Presentatiescherm</h3><p>Standaardduur en hoeveelheid komende wedstrijden.</p></div></div><div className="settings-fields compact"><label>Standaard slide<input type="number" min="3" max="300" value={form.default_slide_seconds} onChange={event => settings.update("default_slide_seconds", numeric(event.target.value))} /><small>seconden</small></label><label>Komende wedstrijden<input type="number" min="1" max="25" value={form.upcoming_match_count} onChange={event => settings.update("upcoming_match_count", numeric(event.target.value))} /><small>wedstrijden</small></label></div></section>
      </div>
    </form>
    <section className="panel court-settings"><div className="settings-section-title"><span>05</span><div><h3>Banen</h3><p>Beheer de banen die beschikbaar zijn voor de planning.</p></div></div><div className="court-setting-list">{settings.courts.map(court => <CourtRow key={court.id} court={court} user={user} saved={settings.courtSaved} onError={settings.setError} />)}</div><form className="add-court-form" onSubmit={settings.createCourt}><div><strong>Nieuwe baan toevoegen</strong><span>Bijvoorbeeld “Baan 3” of “Centre Court”.</span></div><input required value={settings.newCourtName} onChange={event => settings.setNewCourtName(event.target.value)} placeholder="Baannaam" /><input value={settings.newCourtSurface} onChange={event => settings.setNewCourtSurface(event.target.value)} placeholder="Ondergrond (optioneel)" /><button className="primary">＋ Baan toevoegen</button></form></section>
  </div>;
}
