"use client";

import { ManualPlayerModal } from "../Players/ManualPlayerModal";
import type { Player, Sponsor, SponsorTier, StaffUser } from "../shared/types";
import { SponsorModal } from "./SponsorModal";
import { useSponsors } from "./Sponsors.hooks";

export function Sponsors({ user, sponsors, tiers, players, reloadSponsors, reloadPlayers }: { user: StaffUser; sponsors: Sponsor[]; tiers: SponsorTier[]; players: Player[]; reloadSponsors: () => Promise<void>; reloadPlayers: () => Promise<void> }) {
  const controller = useSponsors({ reloadPlayers, reloadSponsors });
  return <><section className="panel full"><div className="table-heading"><div><p>PARTNERS VAN HET TOERNOOI</p><h2>Sponsors</h2></div><button className="primary" onClick={() => controller.setSponsorModal(true)}>＋ Sponsor toevoegen</button></div>{sponsors.length === 0 ? <div className="empty-state"><strong>Nog geen sponsors toegevoegd</strong><span>Voeg eerst een Hoofdsponsor of Subsponsor toe.</span></div> : <div className="sponsor-management-grid">{sponsors.map(sponsor => { const sponsoredPlayers = players.filter(player => player.sponsor_id === sponsor.id); return <article className={`sponsor-management-card ${sponsor.is_active ? "" : "inactive"}`} key={sponsor.id}><div className="sponsor-card-head"><div className="sponsor-logo">{sponsor.name.split(" ").map(part => part[0]).slice(0, 2).join("")}</div><div><span className={sponsor.is_active ? "status paid" : "status pending"}>{sponsor.is_active ? sponsor.tier_name : "Inactief"}</span><h3>{sponsor.name}</h3>{sponsor.website_url && <a href={sponsor.website_url} target="_blank" rel="noreferrer">Website openen ↗</a>}</div><button className="secondary sponsor-edit" onClick={() => controller.setEditingSponsor(sponsor)}>Wijzigen</button></div><div className="sponsor-player-head"><strong>Spelers uit sponsorpakket</strong><span>{sponsoredPlayers.length}</span></div>{sponsoredPlayers.length === 0 ? <p className="sponsor-empty">Nog geen spelers gekoppeld.</p> : <ul className="sponsor-player-list">{sponsoredPlayers.map(player => <li key={player.id}><span>{player.player_number ?? "–"}</span><div><strong>{player.name}</strong><small>{player.email}</small></div><b>Betaald</b></li>)}</ul>}<button className="secondary sponsor-add-player" onClick={() => controller.setPlayerSponsor(sponsor)} disabled={!sponsor.is_active}>＋ Speler toevoegen</button></article>; })}</div>}</section>{controller.sponsorModal && <SponsorModal user={user} tiers={tiers} close={() => controller.setSponsorModal(false)} saved={reloadSponsors} />}{controller.editingSponsor && <SponsorModal user={user} tiers={tiers} sponsor={controller.editingSponsor} close={() => controller.setEditingSponsor(null)} saved={reloadSponsors} />}{controller.playerSponsor && <ManualPlayerModal user={user} sponsors={sponsors} initialSponsorId={String(controller.playerSponsor.id)} close={() => controller.setPlayerSponsor(null)} saved={controller.playerSaved} />}</>;
}
